import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WhatsappLive from "./WhatsappLive";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "C R CAB SERVICE",
  keywords: ["car rental", "cab service", "rent a car", "vehicle rental"],
  authors: [{ name: "C R CAB SERVICE" }],
  creator: "C R CAB SERVICE",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // path relative to public/
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        {children}
        
        <WhatsappLive />
      </body>
    </html>
  );
}
